# Hyprland - configuracion clasica
# DMS usa dispatch clasico de Hyprland, por eso esta configuracion evita la API Lua.

source = ~/.config/hypr/theme.conf
source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/binds.conf
source = ~/.config/hypr/hosts/current.conf

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(7aa2f7ff)
    col.inactive_border = rgba(353d57ff)
    layout = master
}

master {
    mfact = 0.65
    new_status = master
    orientation = left
}

decoration {
    rounding = 8
    blur {
        enabled = false
    }
}

render {
    xp_mode = false
}

animations {
    enabled = true
}

input {
    kb_layout = es
    kb_options = eurosign:e
    follow_mouse = 1
    sensitivity = 0.0

    touchpad {
        natural_scroll = true
        disable_while_typing = true
    }
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}

env = LANG,es_ES.UTF-8
env = LC_ALL,es_ES.UTF-8
